name: todo-pipeline
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    container: golang:1.22.2
    steps:
        - uses: actions/checkout@v4
        - run: |
            git config --global --add safe.directory /__w/YandexPracticum-go-final-TODO/YandexPracticum-go-final-TODO
        - name: Set up Go environment
          run: GOOS=linux GOARCH=amd64 go mod tidy
  
        - name: Build Application
          run: go build -v .
  
        - name: Run Application
          run: ./YandexPracticum-go-final-TODO &
  
        - name: Run Tests
          run: |
            go test  ./tests -v
        - name: Vet
          run: |
            go vet ./...

  lint:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - uses: golangci/golangci-lint-action@v3 
        

  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: alexpop69/yp-final-todo

      - name: Build and push Docker Inage
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}